package com.lotofopps.backend.model;

public enum InvoiceCategory {
    KONTOFUEHRUNGSGEBUEHREN,
    WEGE_ZUR_ARBEIT,
    HOMEOFFICE_UND_ARBEITSZIMMER,
    INTERNET_UND_TELEFON,
    ARBEITSMITTEL,
    BERUFSVERBÄNDE_UND_GEWERKSCHAFTEN,
    STEUERBERATUNGSKOSTEN,
    REISEKOSTEN,
    BEWERBUNGEN,
    FORTBILDUNGEN,
    UMZUG,
    BEWIRTUNG,
    DOPPELTER_HAUSHALT,
    AUSSERGEWOEHNLICHE_FAHRZEUGKOSTEN,
    SONSTIGE_AUSGABEN
}
