loki:
  storageClassName: csi-rbd-sc

kube-prometheus-stack:
  nodeExporter:
    enabled: false
  prometheus-node-exporter:
    enabled: false

  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeEtcd:
    enabled: false

  prometheusOperator:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"

  kube-state-metrics:
    metricLabelsAllowlist:
      - pods=[app.kubernetes.io/name,app.kubernetes.io/version]
    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "50m"
        memory: "128Mi"

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}

      ruleSelectorNilUsesHelmValues: false
      ruleNamespaceSelector: {}
      ruleSelector: {}
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-rbd-sc
            resources:
              requests:
                storage: 5Gi

  alertmanager:
    enabled: true
    alertmanagerSpec:
      secrets:
        - telegram-bot-token
      resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "50m"
          memory: "128Mi"
    config:
      route:
        group_by: ["alertname", "job"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        receiver: telegram
        routes:
          - receiver: "null"
            matchers:
              - alertname = "Watchdog"
      receivers:
        - name: "null"
        - name: telegram
          telegram_configs:
            - chat_id: -5461258895
              bot_token_file: /etc/alertmanager/secrets/telegram-bot-token/token
              parse_mode: HTML
              send_resolved: true
              message: |-
                <b>[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}</b>
                {{ range .Alerts }}{{ .Annotations.summary }}
                {{ end }}

  grafana:
    adminUser: admin
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
    persistence:
      enabled: true
      storageClassName: csi-rbd-sc
      size: 2Gi
    "grafana.ini":
      server:
        domain: taxforward-devops-ss26.stud.k8s.aet.cit.tum.de
        root_url: "%(protocol)s://%(domain)s/grafana/"
        serve_from_sub_path: true
      "auth.anonymous":
        enabled: false
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL
    additionalDataSources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
          tracesToMetrics:
            datasourceUid: prometheus
