CREATE TABLE documents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename       VARCHAR(255) NOT NULL,
    content_type   VARCHAR(255) NOT NULL,
    size_bytes     BIGINT NOT NULL,
    uploaded_at    TIMESTAMP NOT NULL,
    storage_path   VARCHAR(255),
    user_id        VARCHAR(255),
    content_hash   VARCHAR(64)
);

CREATE TABLE invoices (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name     VARCHAR(255) NOT NULL,
    company       VARCHAR(255) NOT NULL,
    price         NUMERIC(10, 2) NOT NULL,
    category      VARCHAR(255) CHECK (category IN (
        'KONTOFUEHRUNGSGEBUEHREN', 'WEGE_ZUR_ARBEIT', 'HOMEOFFICE_UND_ARBEITSZIMMER',
        'INTERNET_UND_TELEFON', 'ARBEITSMITTEL', 'BERUFSVERBÄNDE_UND_GEWERKSCHAFTEN',
        'STEUERBERATUNGSKOSTEN', 'REISEKOSTEN', 'BEWERBUNGEN', 'FORTBILDUNGEN', 'UMZUG',
        'BEWIRTUNG', 'DOPPELTER_HAUSHALT', 'AUSSERGEWOEHNLICHE_FAHRZEUGKOSTEN', 'SONSTIGE_AUSGABEN'
    )),
    status        VARCHAR(255) CHECK (status IN ('PENDING', 'ACCEPTED')),
    user_id       VARCHAR(255),
    document_id   BIGINT REFERENCES documents (id),
    invoice_date  DATE,
    created_at    TIMESTAMP NOT NULL
);

CREATE INDEX idx_invoices_document_id ON invoices (document_id);
