apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxforward.fullname" . }}-client
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: client
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: {{ .Release.Name }}
