apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "taxforward.fullname" . }}-db-suggestions-data
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: db-suggestions
spec:
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dbSuggestions.size | quote }}
