apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxforward.fullname" . }}-db
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: db
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
