apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxforward.fullname" . }}-invoice-service
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: invoice-service
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: invoice-service
    app.kubernetes.io/instance: {{ .Release.Name }}
