apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxforward.fullname" . }}-llm-chat
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: llm-chat
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app.kubernetes.io/name: llm-chat
    app.kubernetes.io/instance: {{ .Release.Name }}
