apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "taxforward.fullname" . }}-seaweedfs-data
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.seaweedfs.size | quote }}
