apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxforward.fullname" . }}-seaweedfs
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: seaweedfs
spec:
  type: ClusterIP
  ports:
    - name: s3
      port: 8333
      targetPort: s3
      protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: {{ .Release.Name }}
