apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taxforward.fullname" . }}-secret
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
type: Opaque
data:
  dbInvoicePassword: {{ .Values.dbInvoice.password | b64enc | quote }}
  dbLlmChatPassword: {{ .Values.dbLlmChat.password | b64enc | quote }}
  dbSuggestionsPassword: {{ .Values.dbSuggestions.password | b64enc | quote }}
  llmApiKey: {{ .Values.llm.apiKey | b64enc | quote }}
{{- if .Values.firebase.serviceAccountJson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taxforward.fullname" . }}-firebase-sa
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
type: Opaque
data:
  firebase-service-account.json: {{ .Values.firebase.serviceAccountJson | b64enc | quote }}
{{- end }}
