apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxforward.fullname" . }}-db-suggestions
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: db-suggestions
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: db-suggestions
    app.kubernetes.io/instance: {{ .Release.Name }}
