apiVersion: v1
kind: Service
metadata:
  name: {{ include "taxforward.fullname" . }}-suggestions-service
  labels:
    {{- include "taxforward.labels" . | nindent 4 }}
    app.kubernetes.io/name: suggestions-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app.kubernetes.io/name: suggestions-service
    app.kubernetes.io/instance: {{ .Release.Name }}
