/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents for the authenticated user */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a document
         * @description Stores the uploaded file, runs AI extraction, and creates the resulting invoices in `PENDING` review state. Allowed content types: PDF, JPEG, PNG, WEBP, TIFF.
         */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a document and all its invoices */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the raw document content */
        get: operations["downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List invoices for the authenticated user
         * @description Optionally filtered by review status and/or invoice year and/or limited to the most recent N results. Defaults to `ACCEPTED` invoices so documents still under review stay hidden.
         */
        get: operations["listInvoices"];
        put?: never;
        /**
         * Manually create a new invoice
         * @description Manually created invoices are accepted immediately (no review step).
         */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an existing invoice */
        put: operations["updateInvoice"];
        post?: never;
        /**
         * Delete an invoice
         * @description Also deletes the associated document if no other invoices reference it.
         */
        delete: operations["deleteInvoice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Keep (accept) an invoice that is under review
         * @description Makes the invoice visible in the list and embeds it for chat retrieval.
         */
        post: operations["acceptInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get proactive tax suggestions
         * @description Suggestions are derived from the user's most recent accepted invoices, most recent first.
         */
        get: operations["getSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the RAG agent a question
         * @description Streams the answer back as Server-Sent Events (`text/event-stream`). Each event is a `data: <json>` line whose payload is an agent event.
         */
        post: operations["agentChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tax years the user has accepted invoices for
         * @description Descending. Invoices without an `invoiceDate` are not attributable to a tax year and are omitted.
         */
        get: operations["listExportYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-category totals for one tax year
         * @description The figures rendered into the PDF summary, exposed separately so the client can preview an export before downloading it.
         */
        get: operations["getExportSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the year's accepted invoices as CSV
         * @description RFC 4180, UTF-8 with a byte-order mark so spreadsheet software reads the German umlauts correctly. One row per invoice line item.
         */
        get: operations["downloadExportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the year's Werbungskosten summary as PDF
         * @description A German-language summary sheet: totals per deduction category, the itemized invoices behind them, and the amount exceeding that year's Arbeitnehmer-Pauschbetrag.
         */
        get: operations["downloadExportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the complete tax-year package as a ZIP archive
         * @description Contains the PDF summary, the CSV and JSON renderings of the invoices, and every original receipt the invoices were extracted from.
         */
        get: operations["downloadExportZip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/invoices/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * [invoice-service] Latest accepted invoices for a user
         * @description Consumed by suggestions-service. Returns only `ACCEPTED` invoices, most recent first. Not exposed through the public gateway.
         */
        get: operations["getLatestInvoicesInternal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * [llm-chat] Update an invoice embedding
         * @description Consumed by invoice-service. Not exposed through the public gateway.
         */
        put: operations["updateEmbedding"];
        /**
         * [llm-chat] Embed an invoice into the chat vector store
         * @description Consumed by invoice-service. Not exposed through the public gateway.
         */
        post: operations["createEmbedding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embed/{invoiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * [llm-chat] Delete an invoice embedding
         * @description Consumed by invoice-service. Not exposed through the public gateway.
         */
        delete: operations["deleteEmbedding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Review state of an invoice.
         * @enum {string}
         */
        InvoiceStatus: "PENDING" | "ACCEPTED";
        /**
         * @description Tax-deductible expense category (German tax terms).
         * @enum {string}
         */
        InvoiceCategory: "KONTOFUEHRUNGSGEBUEHREN" | "WEGE_ZUR_ARBEIT" | "HOMEOFFICE_UND_ARBEITSZIMMER" | "INTERNET_UND_TELEFON" | "ARBEITSMITTEL" | "BERUFSVERBÄNDE_UND_GEWERKSCHAFTEN" | "STEUERBERATUNGSKOSTEN" | "REISEKOSTEN" | "BEWERBUNGEN" | "FORTBILDUNGEN" | "UMZUG" | "BEWIRTUNG" | "DOPPELTER_HAUSHALT" | "AUSSERGEWOEHNLICHE_FAHRZEUGKOSTEN" | "SONSTIGE_AUSGABEN";
        DocumentResponse: {
            /** Format: int64 */
            id: number;
            filename: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: date-time */
            uploadedAt: string;
            userId: string;
        };
        UploadResponse: {
            message: string;
            filename: string;
            /** Format: int64 */
            documentId: number;
            invoiceIds: number[];
        };
        InvoiceRequest: {
            itemName: string;
            company: string;
            price: number;
            category?: (string & components["schemas"]["InvoiceCategory"]) | null;
            /** Format: date */
            invoiceDate?: string | null;
        };
        InvoiceResponse: {
            /** Format: int64 */
            id: number;
            itemName: string;
            company: string;
            price: number;
            category: (string & components["schemas"]["InvoiceCategory"]) | null;
            userId: string;
            /** Format: date */
            invoiceDate: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            documentId: number | null;
            status: components["schemas"]["InvoiceStatus"];
        };
        ExportCategoryTotal: {
            /** @description Null groups the invoices the AI could not categorize. */
            category: (string & components["schemas"]["InvoiceCategory"]) | null;
            invoiceCount: number;
            total: number;
        };
        ExportSummaryResponse: {
            year: number;
            invoiceCount: number;
            /** @description Sum of every accepted invoice dated in this year. */
            totalExpenses: number;
            /** @description The Arbeitnehmer-Pauschbetrag granted for this year without any receipts (§9a EStG). */
            lumpSumAllowance: number;
            /** @description `max(0, totalExpenses - lumpSumAllowance)` — what the collected receipts are worth beyond the automatic allowance. */
            deductibleAboveLumpSum: number;
            categories: components["schemas"]["ExportCategoryTotal"][];
        };
        SuggestionResponse: {
            suggestion: string;
            /** Format: date-time */
            createdAt: string;
        };
        AgentChatRequest: {
            question: string;
        };
        EmbedRequest: {
            /** Format: int64 */
            invoice_id: number;
            text: string;
            user_id: string;
            /** @default N/A */
            item_name: string;
            /** @default N/A */
            company: string;
            price?: number | null;
            category?: string | null;
            invoice_date?: string | null;
            /** Format: int64 */
            document_id?: number | null;
        };
        StatusResponse: {
            /** @example ok */
            status?: string;
        };
        Error: {
            error?: string;
            /**
             * Format: int64
             * @description Present on duplicate-document (409) responses.
             */
            documentId?: number;
        };
    };
    responses: {
        /** @description Missing or invalid Firebase ID token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource belongs to another user */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdPath: number;
        /** @description Tax year, matched against the invoice date. */
        YearQuery: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Document received and processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description No file provided, unsupported type, or file too large */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description A document with identical content already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Failed to store file or extraction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description AI extraction service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content (Content-Type matches the stored document) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                invoiceYear?: number;
                limit?: number;
                status?: components["schemas"]["InvoiceStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getSuggestions: {
        parameters: {
            query?: {
                /** @description ISO language code the suggestions are localized to. */
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    agentChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events stream of agent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listExportYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of years */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getExportSummary: {
        parameters: {
            query: {
                /** @description Tax year, matched against the invoice date. */
                year: components["parameters"]["YearQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary of the year's accepted invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    downloadExportCsv: {
        parameters: {
            query: {
                /** @description Tax year, matched against the invoice date. */
                year: components["parameters"]["YearQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    downloadExportPdf: {
        parameters: {
            query: {
                /** @description Tax year, matched against the invoice date. */
                year: components["parameters"]["YearQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    downloadExportZip: {
        parameters: {
            query: {
                /** @description Tax year, matched against the invoice date. */
                year: components["parameters"]["YearQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ZIP archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLatestInvoicesInternal: {
        parameters: {
            query: {
                userId: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"][];
                };
            };
        };
    };
    updateEmbedding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedRequest"];
            };
        };
        responses: {
            /** @description Embedding updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    createEmbedding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedRequest"];
            };
        };
        responses: {
            /** @description Embedding stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    deleteEmbedding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoiceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Embedding deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
}
