CREATE TABLE suggestions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(255) NOT NULL,
    suggestion   TEXT NOT NULL,
    language     VARCHAR(255),
    created_at   TIMESTAMP NOT NULL
);
