from enum import Enum


class InvoiceCategory(str, Enum):
    KONTOFUEHRUNGSGEBUEHREN = "KONTOFUEHRUNGSGEBUEHREN"
    WEGE_ZUR_ARBEIT = "WEGE_ZUR_ARBEIT"
    HOMEOFFICE_UND_ARBEITSZIMMER = "HOMEOFFICE_UND_ARBEITSZIMMER"
    INTERNET_UND_TELEFON = "INTERNET_UND_TELEFON"
    ARBEITSMITTEL = "ARBEITSMITTEL"
    BERUFSVERBÄNDE_UND_GEWERKSCHAFTEN = "BERUFSVERBÄNDE_UND_GEWERKSCHAFTEN"
    STEUERBERATUNGSKOSTEN = "STEUERBERATUNGSKOSTEN"
    REISEKOSTEN = "REISEKOSTEN"
    BEWERBUNGEN = "BEWERBUNGEN"
    FORTBILDUNGEN = "FORTBILDUNGEN"
    UMZUG = "UMZUG"
    BEWIRTUNG = "BEWIRTUNG"
    DOPPELTER_HAUSHALT = "DOPPELTER_HAUSHALT"
    AUSSERGEWOEHNLICHE_FAHRZEUGKOSTEN = "AUSSERGEWOEHNLICHE_FAHRZEUGKOSTEN"
    SONSTIGE_AUSGABEN = "SONSTIGE_AUSGABEN"
