global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'invoice-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['invoice-service:8080']

  - job_name: 'suggestions-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['suggestions-service:8083']

  - job_name: 'llm-chat'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['llm-chat:8081']

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8000']
