http:
  middlewares:
    firebase-auth:
      forwardAuth:
        address: "http://auth-service:8000/verify"
        authResponseHeaders:
          - "X-User-Sub"

  routers:
    grafana-router:
      rule: "PathPrefix(`/grafana`)"
      entryPoints:
        - web
      service: grafana-svc

    invoice-router:
      rule: "PathPrefix(`/api/v1/documents`) || PathPrefix(`/api/v1/invoices`)"
      entryPoints:
        - web
      middlewares:
        - firebase-auth
      service: invoice-svc

    llm-chat-router:
      rule: "PathPrefix(`/api/v1/agent`)"
      entryPoints:
        - web
      middlewares:
        - firebase-auth
      service: llm-chat-svc

    suggestions-router:
      rule: "PathPrefix(`/api/v1/suggestions`)"
      entryPoints:
        - web
      middlewares:
        - firebase-auth
      service: suggestions-svc

    export-router:
      rule: "PathPrefix(`/api/v1/exports`)"
      entryPoints:
        - web
      middlewares:
        - firebase-auth
      service: export-svc

    client-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: client-svc

  services:
    grafana-svc:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    invoice-svc:
      loadBalancer:
        servers:
          - url: "http://invoice-service:8080"

    llm-chat-svc:
      loadBalancer:
        servers:
          - url: "http://llm-chat:8081"

    suggestions-svc:
      loadBalancer:
        servers:
          - url: "http://suggestions-service:8083"

    export-svc:
      loadBalancer:
        servers:
          - url: "http://export-service:8084"

    client-svc:
      loadBalancer:
        servers:
          - url: "http://client:8080"

