[tox]
envlist = lint, type
skipsdist = true

[testenv:lint]
deps = -r requirements-dev.txt 
commands =
    ruff check app tests
    ruff format --check app tests

[testenv:type]
deps = -r requirements-dev.txt
commands =
    mypy app