# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x17taxforward.embedding.v1\"\xfd\x01\n\x0c\x45mbedRequest\x12\x12\n\ninvoice_id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\titem_name\x18\x04 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x05 \x01(\t\x12\x12\n\x05price\x18\x06 \x01(\x01H\x00\x88\x01\x01\x12\x15\n\x08\x63\x61tegory\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0cinvoice_date\x18\x08 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x64ocument_id\x18\t \x01(\x03H\x03\x88\x01\x01\x42\x08\n\x06_priceB\x0b\n\t_categoryB\x0f\n\r_invoice_dateB\x0e\n\x0c_document_id\"#\n\rDeleteRequest\x12\x12\n\ninvoice_id\x18\x01 \x01(\x03\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb9\x01\n\x10\x45mbeddingService\x12L\n\x05\x45mbed\x12%.taxforward.embedding.v1.EmbedRequest\x1a\x1c.taxforward.embedding.v1.Ack\x12W\n\x0f\x44\x65leteEmbedding\x12&.taxforward.embedding.v1.DeleteRequest\x1a\x1c.taxforward.embedding.v1.AckB\x1e\n\x1a\x63om.lotofopps.backend.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.lotofopps.backend.grpcP\001'
  _globals['_EMBEDREQUEST']._serialized_start=45
  _globals['_EMBEDREQUEST']._serialized_end=298
  _globals['_DELETEREQUEST']._serialized_start=300
  _globals['_DELETEREQUEST']._serialized_end=335
  _globals['_ACK']._serialized_start=337
  _globals['_ACK']._serialized_end=358
  _globals['_EMBEDDINGSERVICE']._serialized_start=361
  _globals['_EMBEDDINGSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
