# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoice.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'invoice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoice.proto\x12\x15taxforward.invoice.v1\":\n\x18GetLatestInvoicesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"M\n\x19GetLatestInvoicesResponse\x12\x30\n\x08invoices\x18\x01 \x03(\x0b\x32\x1e.taxforward.invoice.v1.Invoice\"\xf9\x01\n\x07Invoice\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\t\x12\x19\n\x0cinvoice_date\x18\x07 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ncreated_at\x18\x08 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64ocument_id\x18\t \x01(\x03H\x02\x88\x01\x01\x12\x0e\n\x06status\x18\n \x01(\tB\x0f\n\r_invoice_dateB\r\n\x0b_created_atB\x0e\n\x0c_document_id2\x90\x01\n\x16InternalInvoiceService\x12v\n\x11GetLatestInvoices\x12/.taxforward.invoice.v1.GetLatestInvoicesRequest\x1a\x30.taxforward.invoice.v1.GetLatestInvoicesResponseB\x1e\n\x1a\x63om.lotofopps.backend.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.lotofopps.backend.grpcP\001'
  _globals['_GETLATESTINVOICESREQUEST']._serialized_start=40
  _globals['_GETLATESTINVOICESREQUEST']._serialized_end=98
  _globals['_GETLATESTINVOICESRESPONSE']._serialized_start=100
  _globals['_GETLATESTINVOICESRESPONSE']._serialized_end=177
  _globals['_INVOICE']._serialized_start=180
  _globals['_INVOICE']._serialized_end=429
  _globals['_INTERNALINVOICESERVICE']._serialized_start=432
  _globals['_INTERNALINVOICESERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
