# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import invoice_pb2 as invoice__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in invoice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InternalInvoiceServiceStub:
    """Internal (service-to-service) API served by invoice-service and consumed by
    suggestions-service, llm-chat and export-service. Not exposed publicly via Traefik.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestInvoices = channel.unary_unary(
                '/taxforward.invoice.v1.InternalInvoiceService/GetLatestInvoices',
                request_serializer=invoice__pb2.GetLatestInvoicesRequest.SerializeToString,
                response_deserializer=invoice__pb2.GetLatestInvoicesResponse.FromString,
                _registered_method=True)
        self.GetDocuments = channel.unary_unary(
                '/taxforward.invoice.v1.InternalInvoiceService/GetDocuments',
                request_serializer=invoice__pb2.GetDocumentsRequest.SerializeToString,
                response_deserializer=invoice__pb2.GetDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDocumentContent = channel.unary_unary(
                '/taxforward.invoice.v1.InternalInvoiceService/GetDocumentContent',
                request_serializer=invoice__pb2.GetDocumentContentRequest.SerializeToString,
                response_deserializer=invoice__pb2.GetDocumentContentResponse.FromString,
                _registered_method=True)


class InternalInvoiceServiceServicer:
    """Internal (service-to-service) API served by invoice-service and consumed by
    suggestions-service, llm-chat and export-service. Not exposed publicly via Traefik.
    """

    def GetLatestInvoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalInvoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestInvoices,
                    request_deserializer=invoice__pb2.GetLatestInvoicesRequest.FromString,
                    response_serializer=invoice__pb2.GetLatestInvoicesResponse.SerializeToString,
            ),
            'GetDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocuments,
                    request_deserializer=invoice__pb2.GetDocumentsRequest.FromString,
                    response_serializer=invoice__pb2.GetDocumentsResponse.SerializeToString,
            ),
            'GetDocumentContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentContent,
                    request_deserializer=invoice__pb2.GetDocumentContentRequest.FromString,
                    response_serializer=invoice__pb2.GetDocumentContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taxforward.invoice.v1.InternalInvoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taxforward.invoice.v1.InternalInvoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalInvoiceService:
    """Internal (service-to-service) API served by invoice-service and consumed by
    suggestions-service, llm-chat and export-service. Not exposed publicly via Traefik.
    """

    @staticmethod
    def GetLatestInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxforward.invoice.v1.InternalInvoiceService/GetLatestInvoices',
            invoice__pb2.GetLatestInvoicesRequest.SerializeToString,
            invoice__pb2.GetLatestInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxforward.invoice.v1.InternalInvoiceService/GetDocuments',
            invoice__pb2.GetDocumentsRequest.SerializeToString,
            invoice__pb2.GetDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxforward.invoice.v1.InternalInvoiceService/GetDocumentContent',
            invoice__pb2.GetDocumentContentRequest.SerializeToString,
            invoice__pb2.GetDocumentContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
